# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatter',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='is_loud',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='chatters',
            field=models.ManyToManyField(to='chat.Chatter'),
        ),
    ]
